"""add staged_attachments table

Revision ID: 08828cd4e8ca
Revises: 2b407df3b1b5
Create Date: 2026-03-31 12:09:53.320698

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '08828cd4e8ca'
down_revision: str | Sequence[str] | None = '2b407df3b1b5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staged_attachments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bank_code', sa.Text(), nullable=False),
    sa.Column('gmail_message_id', sa.Text(), nullable=False),
    sa.Column('gmail_attachment_id', sa.Text(), nullable=False),
    sa.Column('message_date', sa.DateTime(), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=False),
    sa.Column('staged_path', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('error_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gmail_message_id', 'gmail_attachment_id', name='uq_staged_gmail_attachment')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staged_attachments')
    # ### end Alembic commands ###
